In [1]:
from transformers import AutoTokenizer
from transformers import TFAutoModelForSequenceClassification

In [2]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

OSError: Exception encountered when calling layer "transformer" (type TFTransformer).

22

Call arguments received:
  • x=tf.Tensor(shape=(3, 5, 768), dtype=float32)
  • attn_mask=tf.Tensor(shape=(3, 5), dtype=float32)
  • head_mask=['None', 'None', 'None', 'None', 'None', 'None']
  • output_attentions=False
  • output_hidden_states=False
  • return_dict=True
  • training=False

In [12]:
raw_inputs = [
    "I love apostle's message, it is always spirit filled", 
    "Landmark university has good discipline, but the staffs make the school unbearable"
]

In [13]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='tf')
outputs = model(inputs)

In [14]:
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1045,  2293, 20121,  1005,  1055,  4471,  1010,  2009,
         2003,  2467,  4382,  3561,   102,     0,     0],
       [  101,  8637,  2118,  2038,  2204,  9009,  1010,  2021,  1996,
         3095,  2015,  2191,  1996,  2082, 24257,   102]])>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}


In [23]:
print(outputs.last_hidden_state)

tf.Tensor(
[[[ 0.37385613  0.0119298   0.23416589 ...  0.3183204   0.98529905
   -0.49220636]
  [ 0.70384085  0.3422688   0.19230537 ...  0.3343934   1.1143095
   -0.38301998]
  [ 0.856921    0.44062868  0.34573278 ...  0.32101107  1.0842397
   -0.3419956 ]
  ...
  [ 1.2280487   0.14038359  0.6596221  ...  0.613811    0.7697899
   -0.88743466]
  [ 0.31570143 -0.13121307  0.12153672 ...  0.42600983  0.9004798
   -0.27304545]
  [ 0.37800097 -0.04787834  0.07781225 ...  0.45051974  0.88421273
   -0.19998364]]

 [[-0.43699124  0.7372221   0.18917045 ... -0.17812465 -0.1702532
   -0.18818647]
  [ 0.12658073  1.229425    0.27286214 ... -0.230544    0.80006886
   -0.43952012]
  [-0.2446475   1.0670198   0.1162011  ... -0.21610022  0.87253255
    0.15578657]
  ...
  [-0.36935547  0.9202494   0.22073224 ... -0.14819282 -0.37498474
   -0.0406535 ]
  [-0.6024419   0.83799136  0.26293394 ... -0.08752455 -0.3994203
   -0.37209523]
  [-0.09525004  1.0783511   0.13140976 ... -0.3621051  -0.28675422
 